// Code generated by MockGen. DO NOT EDIT.
// Source: ./itf.go
//
// Generated by this command:
//
//	mockgen -source=./itf.go -destination=./mock.go -package=mymock
//

// Package mymock is a generated GoMock package.
package mygomock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFoo is a mock of Foo interface.
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *MockFooMockRecorder
	isgomock struct{}
}

// MockFooMockRecorder is the mock recorder for MockFoo.
type MockFooMockRecorder struct {
	mock *MockFoo
}

// NewMockFoo creates a new mock instance.
func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &MockFooMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo) EXPECT() *MockFooMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockFoo) Bar(x int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bar", x)
	ret0, _ := ret[0].(int)
	return ret0
}

// Bar indicates an expected call of Bar.
func (mr *MockFooMockRecorder) Bar(x any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bar", reflect.TypeOf((*MockFoo)(nil).Bar), x)
}

// MockDealer is a mock of Dealer interface.
type MockDealer struct {
	ctrl     *gomock.Controller
	recorder *MockDealerMockRecorder
	isgomock struct{}
}

// MockDealerMockRecorder is the mock recorder for MockDealer.
type MockDealerMockRecorder struct {
	mock *MockDealer
}

// NewMockDealer creates a new mock instance.
func NewMockDealer(ctrl *gomock.Controller) *MockDealer {
	mock := &MockDealer{ctrl: ctrl}
	mock.recorder = &MockDealerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDealer) EXPECT() *MockDealerMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockDealer) Evaluate(c *Car) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", c)
	ret0, _ := ret[0].(int)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockDealerMockRecorder) Evaluate(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockDealer)(nil).Evaluate), c)
}
